# Add a line between prompts
add_newline = true

# Show hostname
[hostname]
ssh_only = false
format = "[$hostname](bold purple) "
disabled = false

# Change character to show in place of >
[character]
success_symbol = "[Î» ](bold green)"
error_symbol = "[Î» ](bold red)"

# Disable package module
[package]
disabled = true

# See battery status
[battery]
full_symbol = "âš¡ï¸ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "


#-------- Git configuration ##

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "
